### ISSUE TITLE
Voice Fill icon from the toolbar is barely visible with Dark Theme enabled

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#229]
[Affected versions]:
- Firefox 56.0.2 and up
- Voice Fill v.1.3.4

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the Voice Fill (v. 1.3.4) experiment installed.
- Have Dark Theme enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the "Voice Fill" toolbar button.

[Expected result]:
- The "Voice Fill" toolbar button is correctly displayed.

[Actual result]:
- The "Voice Fill" toolbar button is barely visible.

[Notes]:
- Attached a screen recording of the issue:

![dark theme](https://user-images.githubusercontent.com/26000308/32333520-d562beec-bff0-11e7-8d30-3ac6eb7ca495.gif)

**Comment by andrenatal** [comment]
@johngruen what should we use here?

**Comment by johngruen** [comment]
should now be resolved

**Comment by SoftVision-CarmenFat** [comment]
This issue is still reproducible with the pre-release version (v.1.3.5).

**Comment by andrenatal** [comment]
Carmen, I could not reproduce this issue using the latest xpi. Please, check the screen cast here: https://www.dropbox.com/s/82spwwbtv6nsoyd/icon-issue.mov?dl=0

**Comment by SoftVision-CarmenFat** [comment]
After digging more into this issue, I found out that this is reproducible only with Windows and Ubuntu. On macOS, the icon is correctly displayed in the toolbar when Dark theme is enabled.

**Comment by andrenatal** [comment]
Hi Carmen, could you please test this again with 1.3.6?

**Comment by SoftVision-CarmenFat** [comment]
Tested this with Voice Fill v.1.3.6 and I can confirm that the issue is fixed: the icon is now correctly displayed across platforms when Dark theme is enabled.

**Comment by Softvision-CristinaBadescu** [comment]
Indeed, this issue has been fixed but not entirely. It seems that the default buttons color on dark theme is BEBEBE while this fix makes "Voice Fill" button D1D1D2, which is a little bit lighter. Considering this, I'm going to reopen this issue.
Below is a screenshot with the colors codes for the buttons:
![button colors](https://user-images.githubusercontent.com/31244235/35053375-973515ae-fbb2-11e7-9ad7-58296dd30184.png)
